# Generated by Django 4.0.6 on 2022-07-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='moded',
            new_name='model',
        ),
    ]
